# -*- coding: utf-8 -*-
"""jobstreet_all.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PzGcCcfSxBqYafEWA6kZEVeAabeE_byP
"""

import requests
import pandas as pd
import time
import random

from bs4 import BeautifulSoup


# =====================================================
# SETTINGS
# =====================================================
OUTPUT_FILE = "jobstreet_ALL.csv"

MAX_EMPTY_PAGES = 3

MAX_RETRIES = 3

SLEEP_MIN = 2
SLEEP_MAX = 5


# =====================================================
# COUNTRIES
# =====================================================
COUNTRIES = {

    "Malaysia":
    "https://my.jobstreet.com/jobs/in-Malaysia",

    "Singapore":
    "https://my.jobstreet.com/jobs/in-Singapore",

    "Indonesia":
    "https://my.jobstreet.com/jobs/in-Indonesia",

    "Thailand":
    "https://my.jobstreet.com/jobs/in-Thailand",

    "Philippines":
    "https://my.jobstreet.com/jobs/in-Philippines"
}


# =====================================================
# KEYWORDS
# =====================================================
KEYWORDS = [

    "python",
    "java",
    "software engineer",
    "data analyst",
    "data engineer",
    "machine learning",
    "ai engineer",
    "cyber security",
    "cloud engineer",
    "aws",
    "devops",
    "frontend developer",
    "backend developer",
    "full stack developer",
    "react developer",
    "sql",
    "power bi",
    "tableau",
    "sap",
    "network engineer",
    "system engineer",
    "business analyst",
    "mobile developer",
    "ios developer",
    "android developer",
    "accounting",
    "finance",
    "marketing",
    "sales",
    "human resources",
    "engineering",
    "healthcare",
    "retail",
    "logistics"
]


# =====================================================
# USER AGENTS
# =====================================================
USER_AGENTS = [

    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0 Safari/537.36",

    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0 Safari/537.36",

    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36"
]


# =====================================================
# HEADERS
# =====================================================
def get_headers():

    return {

        "User-Agent":
        random.choice(USER_AGENTS),

        "Accept-Language":
        "en-US,en;q=0.9",

        "Referer":
        "https://www.google.com/"
    }


# =====================================================
# FETCH PAGE
# =====================================================
def fetch_page(url):

    for attempt in range(1, MAX_RETRIES + 1):

        try:

            response = requests.get(

                url,

                headers=get_headers(),

                timeout=30
            )

            if response.status_code == 200:

                return response.text

            else:

                print(

                    f"  [HTTP {response.status_code}] "
                    f"Attempt {attempt}/{MAX_RETRIES}"
                )

                time.sleep(5)

        except Exception as e:

            print("Request Error:", e)

            time.sleep(5)

    return None


# =====================================================
# EXTRACT JOBS
# =====================================================
def extract_jobs(url, country, keyword):

    jobs = []

    html = fetch_page(url)

    if not html:

        print(f"  Could not fetch: {url}")

        return jobs

    soup = BeautifulSoup(
        html,
        "html.parser"
    )

    job_cards = soup.find_all("article")

    print(f"  Found {len(job_cards)} job cards")

    if len(job_cards) == 0:

        return jobs

    # =================================================
    # LOOP JOB CARDS
    # =================================================
    for card in job_cards:

        # -------------------------------------------------
        # TITLE
        # -------------------------------------------------
        try:

            title_tag = card.find(

                "a",

                attrs={
                    "data-automation":
                    "jobTitle"
                }
            )

            title = title_tag.get_text(
                strip=True
            )

        except:

            title = "N/A"

        # -------------------------------------------------
        # COMPANY
        # -------------------------------------------------
        try:

            company = "N/A"

            selectors = [

                {
                    "data-automation":
                    "advertiser-name"
                },

                {
                    "data-automation":
                    "jobCompany"
                }
            ]

            for selector in selectors:

                company_tag = card.find(
                    attrs=selector
                )

                if company_tag:

                    company = (
                        company_tag
                        .get_text(strip=True)
                    )

                    break

        except:

            company = "N/A"

        # -------------------------------------------------
        # LOCATION
        # -------------------------------------------------
        try:

            location = "N/A"

            selectors = [

                {
                    "data-automation":
                    "job-location"
                },

                {
                    "data-automation":
                    "jobLocation"
                }
            ]

            for selector in selectors:

                location_tag = card.find(
                    attrs=selector
                )

                if location_tag:

                    location = (
                        location_tag
                        .get_text(strip=True)
                    )

                    break

        except:

            location = "N/A"

        # -------------------------------------------------
        # SALARY
        # -------------------------------------------------
        try:

            salary = "N/A"

            selectors = [

                {
                    "data-automation":
                    "job-card-salary"
                },

                {
                    "data-automation":
                    "jobSalary"
                }
            ]

            for selector in selectors:

                salary_tag = card.find(
                    attrs=selector
                )

                if salary_tag:

                    salary = (
                        salary_tag
                        .get_text(strip=True)
                    )

                    break

        except:

            salary = "N/A"

        # -------------------------------------------------
        # POSTED DATE
        # -------------------------------------------------
        try:

            posted_tag = card.find(

                attrs={
                    "data-automation":
                    "jobListingDate"
                }
            )

            posted = posted_tag.get_text(
                strip=True
            )

        except:

            posted = "N/A"

        # -------------------------------------------------
        # EMPLOYMENT TYPE
        # -------------------------------------------------
        try:

            employment = "N/A"

            employment_keywords = [

                "Full time",
                "Part time",
                "Contract",
                "Internship",
                "Temporary"
            ]

            text = card.get_text(
                " ",
                strip=True
            )

            for emp in employment_keywords:

                if emp.lower() in text.lower():

                    employment = emp

                    break

        except:

            employment = "N/A"

        # -------------------------------------------------
        # URL
        # -------------------------------------------------
        try:

            link = title_tag["href"]

            if not link.startswith("http"):

                COUNTRY_DOMAINS = {

                    "Malaysia":
                    "https://my.jobstreet.com/jobs/in-Malaysia",

                    "Singapore":
                    "https://my.jobstreet.com/jobs/in-Singapore",

                    "Indonesia":
                    "https://my.jobstreet.com/jobs/in-Indonesia",

                    "Thailand":
                    "https://my.jobstreet.com/jobs/in-Thailand",

                    "Philippines":
                    "https://my.jobstreet.com/jobs/in-Philippines"
                }

                base = COUNTRY_DOMAINS.get(
                    country,
                    "https://my.jobstreet.com"
                )

                link = base + link

        except:

            link = "N/A"

        # -------------------------------------------------
        # APPEND
        # -------------------------------------------------
        jobs.append({

            "Country":
            country,

            "Keyword":
            keyword,

            "Title":
            title,

            "Company":
            company,

            "Location":
            location,

            "Salary":
            salary,

            "Posted":
            posted,

            "Employment Type":
            employment,

            "URL":
            link
        })

    return jobs


# =====================================================
# SAVE CSV
# =====================================================
def save_csv(all_jobs):

    df = pd.DataFrame(all_jobs)

    if not df.empty:

        before = len(df)

        df = df.drop_duplicates(
            subset=["URL"]
        )

        after = len(df)

        print(
            f"  Removed "
            f"{before - after} duplicates"
        )

    df.to_csv(

        OUTPUT_FILE,

        index=False,

        encoding="utf-8-sig"
    )

    print(
        f"  [Saved] "
        f"{len(df)} unique jobs "
        f"→ {OUTPUT_FILE}"
    )


# =====================================================
# MAIN
# =====================================================
def main():

    all_jobs = []

    # =================================================
    # COUNTRY LOOP
    # =================================================
    for country, domain in COUNTRIES.items():

        print("\n" + "="*60)

        print(f"SCRAPING {country}")

        print("="*60)

        # =============================================
        # KEYWORD LOOP
        # =============================================
        for keyword in KEYWORDS:

            print(f"\nKEYWORD: {keyword}")

            page = 1

            consecutive_empty = 0

            # =========================================
            # PAGE LOOP
            # =========================================
            while True:

                print(f"\nPage {page}")

                keyword_slug = (
                    keyword
                    .replace(" ", "-")
                    .lower()
                )

                url = (

                    f"{domain}/"

                    f"{keyword_slug}-jobs"

                    f"?page={page}"
                )

                jobs = extract_jobs(

                    url,

                    country,

                    keyword
                )

                count = len(jobs)

                all_jobs.extend(jobs)

                print(

                    f"  Extracted {count} jobs"

                    f"  |  Total so far: "
                    f"{len(all_jobs)}"
                )

                # =====================================
                # STOP CONDITION
                # =====================================
                if count == 0:

                    consecutive_empty += 1

                    print(

                        f"  Empty page "
                        f"({consecutive_empty}/"
                        f"{MAX_EMPTY_PAGES})"
                    )

                    if (
                        consecutive_empty
                        >= MAX_EMPTY_PAGES
                    ):

                        print(
                            f"  Stopping "
                            f"{keyword}"
                        )

                        break

                else:

                    consecutive_empty = 0

                # =====================================
                # SAVE CSV
                # =====================================
                if len(all_jobs) % 500 < count:

                    save_csv(all_jobs)

                # =====================================
                # COOL DOWN
                # =====================================
                if page % 100 == 0:

                    print(
                        "\nCooling down "
                        "for 60 seconds...\n"
                    )

                    time.sleep(60)

                time.sleep(

                    random.uniform(
                        SLEEP_MIN,
                        SLEEP_MAX
                    )
                )

                page += 1

    # =================================================
    # FINAL SAVE
    # =================================================
    print("\n" + "="*60)

    print("FINALISING DATASET...")

    save_csv(all_jobs)

    print("\nDONE!")


# =====================================================
# RUN
# =====================================================
if __name__ == "__main__":

    main()
